---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1qrg4hjfmt4gc4x3tt07pqx795t6vy93qcz5lhavtwcsxuk3029dsvlngka"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1qrg4hjfmt4gc4x3tt07pqx795t6vy93qcz5lhavtwcsxuk3029dsvlngka"
stores:
  yaml:
    indent: 2
